// Code generated by peg -inline -switch grammar.peg. DO NOT EDIT.

package pdr

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"slices"
	"strconv"
	"time"
)

const endSymbol rune = 1114112

/* The rule types inferred from the grammar are below. */
type pegRule uint8

const (
	ruleUnknown pegRule = iota
	ruleQuery
	ruleExpr
	ruleNOW
	rulePAST
	ruleFUTURE
	ruleEVERYTHING
	ruleNumber
	ruleYEARS
	ruleQUARTERS
	ruleMONTHS
	ruleWEEKS
	ruleLAST
	ruleCURRENT
	ruleTODATE
	ruleNEXT
	rule_
	ruleWhitespace
	ruleEOL
	ruleEOF
	ruleAction0
	ruleAction1
	ruleAction2
	ruleAction3
	ruleAction4
	ruleAction5
	ruleAction6
	ruleAction7
	ruleAction8
	ruleAction9
	ruleAction10
	ruleAction11
	rulePegText
	ruleAction12
	ruleAction13
	ruleAction14
	ruleAction15
	ruleAction16
	ruleAction17
	ruleAction18
	ruleAction19
	ruleAction20
	ruleAction21
	ruleAction22
	ruleAction23
	ruleAction24
	ruleAction25
	ruleAction26
	ruleAction27
	ruleAction28
	ruleAction29
	ruleAction30
	ruleAction31
	ruleAction32
)

var rul3s = [...]string{
	"Unknown",
	"Query",
	"Expr",
	"NOW",
	"PAST",
	"FUTURE",
	"EVERYTHING",
	"Number",
	"YEARS",
	"QUARTERS",
	"MONTHS",
	"WEEKS",
	"LAST",
	"CURRENT",
	"TODATE",
	"NEXT",
	"_",
	"Whitespace",
	"EOL",
	"EOF",
	"Action0",
	"Action1",
	"Action2",
	"Action3",
	"Action4",
	"Action5",
	"Action6",
	"Action7",
	"Action8",
	"Action9",
	"Action10",
	"Action11",
	"PegText",
	"Action12",
	"Action13",
	"Action14",
	"Action15",
	"Action16",
	"Action17",
	"Action18",
	"Action19",
	"Action20",
	"Action21",
	"Action22",
	"Action23",
	"Action24",
	"Action25",
	"Action26",
	"Action27",
	"Action28",
	"Action29",
	"Action30",
	"Action31",
	"Action32",
}

type Uint interface {
	~uint | ~uint8 | ~uint16 | ~uint32 | ~uint64
}

type token[U Uint] struct {
	pegRule
	begin, end U
}

func (t *token[_]) String() string {
	// \x1B[34m = blue
	// \x1B[m   = normal (disable color)
	return fmt.Sprintf("\x1B[34m%v\x1B[m %v %v", rul3s[t.pegRule], t.begin, t.end)
}

type node[U Uint] struct {
	token[U]
	up, next *node[U]
}

func (n *node[U]) print(w io.Writer, pretty bool, buffer string) {
	var printFunc func(n *node[U], depth int)
	printFunc = func(n *node[U], depth int) {
		for n != nil {
			for range depth {
				fmt.Fprint(w, " ")
			}
			rule := rul3s[n.pegRule]
			quote := strconv.Quote(string([]rune(buffer)[n.begin:n.end]))
			if !pretty {
				fmt.Fprintf(w, "%v %v\n", rule, quote)
			} else {
				fmt.Fprintf(w, "\x1B[36m%v\x1B[m %v\n", rule, quote)
			}
			if n.up != nil {
				printFunc(n.up, depth+1)
			}
			n = n.next
		}
	}
	printFunc(n, 0)
}

func (n *node[_]) Print(w io.Writer, buffer string) {
	n.print(w, false, buffer)
}

func (n *node[_]) PrettyPrint(w io.Writer, buffer string) {
	n.print(w, true, buffer)
}

type tokens[U Uint] struct {
	tree []token[U]
}

func (t *tokens[_]) Trim(length uint32) {
	t.tree = t.tree[:length]
}

func (t *tokens[_]) Print() {
	for _, token := range t.tree {
		fmt.Println(token.String())
	}
}

func (t *tokens[U]) AST() *node[U] {
	type element struct {
		node *node[U]
		down *element
	}
	tokenSlice := t.Tokens()
	var stack *element
	for _, token := range tokenSlice {
		if token.begin == token.end {
			continue
		}
		node := &node[U]{token: token}
		for stack != nil && stack.node.begin >= token.begin && stack.node.end <= token.end {
			stack.node.next = node.up
			node.up = stack.node
			stack = stack.down
		}
		stack = &element{node: node, down: stack}
	}
	if stack != nil {
		return stack.node
	}
	return nil
}

func (t *tokens[_]) PrintSyntaxTree(buffer string) {
	t.AST().Print(os.Stdout, buffer)
}

func (t *tokens[_]) WriteSyntaxTree(w io.Writer, buffer string) {
	t.AST().Print(w, buffer)
}

func (t *tokens[_]) PrettyPrintSyntaxTree(buffer string) {
	t.AST().PrettyPrint(os.Stdout, buffer)
}

func (t *tokens[U]) Add(rule pegRule, begin, end, index U) {
	tree, i := t.tree, int(index)
	newToken := token[U]{pegRule: rule, begin: begin, end: end}

	if i >= len(tree) {
		t.tree = append(tree, newToken)
		return
	}
	tree[i] = newToken
}

func (t *tokens[U]) Tokens() []token[U] {
	return t.tree
}

type parser[U Uint] struct {
	currentTime time.Time
	start       time.Time
	end         time.Time
	number      int

	Buffer         string
	buffer         []rune
	rules          [54]func() bool
	parse          func(rule ...int) error
	reset          func()
	Pretty         bool
	disableMemoize bool
	tokens[U]
}

func (p *parser[_]) Parse(rule ...int) error {
	return p.parse(rule...)
}

func (p *parser[_]) Reset() {
	p.reset()
}

type textPosition struct {
	line, symbol int
}

type textPositionMap map[int]textPosition

func translatePositions(buffer []rune, positions []int) textPositionMap {
	length := len(positions)
	translations := make(textPositionMap, length)
	posIdx := 0
	line := 1
	symbol := 0

	slices.Sort(positions)

	for i, c := range buffer {
		if c == '\n' {
			line, symbol = line+1, 0
		} else {
			symbol++
		}
		if i == positions[posIdx] {
			translations[positions[posIdx]] = textPosition{line, symbol}
			for posIdx++; posIdx < length; posIdx++ {
				if i == positions[posIdx] {
					return translations
				}
			}
		}
		if posIdx >= length {
			break
		}
	}

	return translations
}

type parseError[U Uint] struct {
	p        *parser[U]
	maxToken token[U]
}

func (e *parseError[U]) Error() string {
	tokenSlice, err := []token[U]{e.maxToken}, "\n"
	positions, p := make([]int, 2*len(tokenSlice)), 0
	for _, t := range tokenSlice {
		positions[p], p = int(t.begin), p+1
		positions[p], p = int(t.end), p+1
	}
	translations := translatePositions(e.p.buffer, positions)
	format := "parse error near %v (line %v symbol %v - line %v symbol %v):\n%v\n"
	if e.p.Pretty {
		format = "parse error near \x1B[34m%v\x1B[m (line %v symbol %v - line %v symbol %v):\n%v\n"
	}
	for _, t := range tokenSlice {
		begin, end := int(t.begin), int(t.end)
		err += fmt.Sprintf(format,
			rul3s[t.pegRule],
			translations[begin].line, translations[begin].symbol,
			translations[end].line, translations[end].symbol,
			strconv.Quote(string(e.p.buffer[begin:end])))
	}

	return err
}

func (p *parser[_]) PrintSyntaxTree() {
	if p.Pretty {
		p.tokens.PrettyPrintSyntaxTree(p.Buffer)
	} else {
		p.tokens.PrintSyntaxTree(p.Buffer)
	}
}

func (p *parser[_]) WriteSyntaxTree(w io.Writer) {
	p.tokens.WriteSyntaxTree(w, p.Buffer)
}

func (p *parser[_]) SprintSyntaxTree() string {
	var b bytes.Buffer
	p.WriteSyntaxTree(&b)
	return b.String()
}

func (p *parser[_]) Execute() {
	buffer, _buffer, text, begin, end := p.Buffer, p.buffer, "", 0, 0
	for _, t := range p.Tokens() {
		switch t.pegRule {

		case rulePegText:
			begin, end = int(t.begin), int(t.end)
			text = string(_buffer[begin:end])

		case ruleAction0:

			p.start, p.end = boundsYear(p.currentTime)

		case ruleAction1:

			p.start, p.end = boundsQuarter(p.currentTime)

		case ruleAction2:

			p.start, p.end = boundsMonth(p.currentTime)

		case ruleAction3:

			p.start, p.end = boundsYear(p.currentTime)
			if p.number > 1 {
				p.start = p.start.AddDate(-1*(p.number-1), 0, 0)
			} else {
				p.end = p.start
				p.start = p.start.AddDate(-1, 0, 0)
			}

		case ruleAction4:

			p.start, p.end = boundsQuarter(p.currentTime)
			if p.number > 1 {
				p.start = p.start.AddDate(0, -3*(p.number-1), 0)
			} else {
				p.end = p.start
				p.start = p.start.AddDate(0, -3, 0)
			}

		case ruleAction5:

			p.start, p.end = boundsMonth(p.currentTime)
			if p.number > 1 {
				p.start = p.start.AddDate(0, -1*(p.number-1), 0)
			} else {
				p.end = p.start
				p.start = p.start.AddDate(0, -1, 0)
			}

		case ruleAction6:

			p.start, p.end = boundsWeek(p.currentTime)
			if p.number > 1 {
				p.start = p.start.AddDate(0, 0, -7*(p.number-1))
			} else {
				p.end = p.start
				p.start = p.start.AddDate(0, 0, -7)
			}

		case ruleAction7:

			p.start, p.end = boundsYear(p.currentTime)
			if p.number > 1 {
				p.end = p.start.AddDate(p.number, 0, 0)
			} else {
				p.start = p.end
				p.end = p.start.AddDate(1, 0, 0)
			}

		case ruleAction8:

			p.start, p.end = boundsQuarter(p.currentTime)
			if p.number > 1 {
				p.end = p.start.AddDate(0, 3*(p.number), 0)
			} else {
				p.start = p.start.AddDate(0, 3, 0)
				p.end = p.start.AddDate(0, 3, 0)
			}

		case ruleAction9:

			p.start, p.end = boundsMonth(p.currentTime)
			if p.number > 1 {
				p.end = p.start.AddDate(0, p.number, 0)
			} else {
				p.start = p.end
				p.end = p.start.AddDate(0, 1, 0)
			}

		case ruleAction10:

			p.start, p.end = boundsWeek(p.currentTime)
			if p.number > 1 {
				p.end = p.start.AddDate(0, 0, 7*p.number)
			} else {
				p.start = p.end
				p.end = p.start.AddDate(0, 0, 7)
			}

		case ruleAction11:

			p.start = time.Time{}
			p.end = p.currentTime.Add(1<<63 - 1)

		case ruleAction12:
			n, _ := strconv.Atoi(text)
			p.number = n
		case ruleAction13:
			p.number = 1
		case ruleAction14:
			p.number = 2
		case ruleAction15:
			p.number = 3
		case ruleAction16:
			p.number = 4
		case ruleAction17:
			p.number = 5
		case ruleAction18:
			p.number = 6
		case ruleAction19:
			p.number = 7
		case ruleAction20:
			p.number = 8
		case ruleAction21:
			p.number = 9
		case ruleAction22:
			p.number = 10
		case ruleAction23:
			p.number = 11
		case ruleAction24:
			p.number = 12
		case ruleAction25:
			p.number = 13
		case ruleAction26:
			p.number = 14
		case ruleAction27:
			p.number = 15
		case ruleAction28:
			p.number = 16
		case ruleAction29:
			p.number = 17
		case ruleAction30:
			p.number = 18
		case ruleAction31:
			p.number = 19
		case ruleAction32:
			p.number = 20

		}
	}
	_, _, _, _, _ = buffer, _buffer, text, begin, end
}

func Pretty[U Uint](pretty bool) func(*parser[U]) error {
	return func(p *parser[U]) error {
		p.Pretty = pretty
		return nil
	}
}

func Size[U Uint](size int) func(*parser[U]) error {
	return func(p *parser[U]) error {
		p.tokens = tokens[U]{tree: make([]token[U], 0, size)}
		return nil
	}
}

func DisableMemoize[U Uint]() func(*parser[U]) error {
	return func(p *parser[U]) error {
		p.disableMemoize = true
		return nil
	}
}

type memo[U Uint] struct {
	Matched bool
	Partial []token[U]
}

type memoKey[U Uint] struct {
	Rule     U
	Position U
}

func (p *parser[U]) Init(options ...func(*parser[U]) error) error {
	var (
		maxToken             token[U]
		position, tokenIndex U
		buffer               []rune
		memoization          map[memoKey[U]]memo[U]
	)
	for _, option := range options {
		err := option(p)
		if err != nil {
			return err
		}
	}
	p.reset = func() {
		maxToken = token[U]{}
		position, tokenIndex = 0, 0
		memoization = make(map[memoKey[U]]memo[U])
		p.buffer = []rune(p.Buffer)
		if len(p.buffer) == 0 || p.buffer[len(p.buffer)-1] != endSymbol {
			p.buffer = append(p.buffer, endSymbol)
		}
		buffer = p.buffer
	}
	p.reset()

	_rules := p.rules
	tree := p.tokens
	p.parse = func(rule ...int) error {
		r := 1
		if len(rule) > 0 {
			r = rule[0]
		}
		matches := p.rules[r]()
		p.tokens = tree
		if matches {
			p.Trim(uint32(tokenIndex))
			return nil
		}
		return &parseError[U]{p, maxToken}
	}

	add := func(rule pegRule, begin U) {
		tree.Add(rule, begin, position, tokenIndex)
		tokenIndex++
		if begin != position && position > maxToken.end {
			maxToken = token[U]{rule, begin, position}
		}
	}

	memoize := func(rule U, begin U, tokenIndexStart U, matched bool) {
		if p.disableMemoize {
			return
		}
		key := memoKey[U]{rule, begin}
		if !matched {
			memoization[key] = memo[U]{Matched: false}
		} else {
			memoization[key] = memo[U]{
				Matched: true,
				Partial: slices.Clone(tree.tree[tokenIndexStart:tokenIndex]),
			}
		}
	}

	memoizedResult := func(m memo[U]) bool {
		if !m.Matched {
			return false
		}
		tree.tree = append(tree.tree[:tokenIndex], m.Partial...)
		tokenIndex += U(len(m.Partial))
		position = m.Partial[len(m.Partial)-1].end
		if tree.tree[tokenIndex-1].begin != position && position > maxToken.end {
			maxToken = tree.tree[tokenIndex-1]
		}
		return true
	}

	matchDot := func() bool {
		if buffer[position] != endSymbol {
			position++
			return true
		}
		return false
	}

	_rules = [...]func() bool{
		nil,

		/* 0 Query <- <(Expr EOF)> */
		func() bool {
			if memoized, ok := memoization[memoKey[U]{0, position}]; ok {
				return memoizedResult(memoized)
			}
			position0, tokenIndex0 := position, tokenIndex
			{
				position1 := position
				{
					position2 := position
					{
						switch buffer[position] {
						case 'a', 'e', 'f':
							{
								position4 := position
								{
									switch buffer[position] {
									case 'e':
										position++
										if buffer[position] != 'v' {
											goto l0
										}
										position++
										if buffer[position] != 'e' {
											goto l0
										}
										position++
										if buffer[position] != 'r' {
											goto l0
										}
										position++
										if buffer[position] != 'y' {
											goto l0
										}
										position++
										if buffer[position] != 't' {
											goto l0
										}
										position++
										if buffer[position] != 'h' {
											goto l0
										}
										position++
										if buffer[position] != 'i' {
											goto l0
										}
										position++
										if buffer[position] != 'n' {
											goto l0
										}
										position++
										if buffer[position] != 'g' {
											goto l0
										}
										position++
									case 'f':
										position++
										if buffer[position] != 'o' {
											goto l0
										}
										position++
										if buffer[position] != 'r' {
											goto l0
										}
										position++
										if buffer[position] != 'e' {
											goto l0
										}
										position++
										if buffer[position] != 'v' {
											goto l0
										}
										position++
										if buffer[position] != 'e' {
											goto l0
										}
										position++
										if buffer[position] != 'r' {
											goto l0
										}
										position++
									default:
										if buffer[position] != 'a' {
											goto l0
										}
										position++
										if buffer[position] != 'l' {
											goto l0
										}
										position++
										if buffer[position] != 'l' {
											goto l0
										}
										position++
										if buffer[position] != ' ' {
											goto l0
										}
										position++
										if buffer[position] != 't' {
											goto l0
										}
										position++
										if buffer[position] != 'i' {
											goto l0
										}
										position++
										if buffer[position] != 'm' {
											goto l0
										}
										position++
										if buffer[position] != 'e' {
											goto l0
										}
										position++
									}
								}

								_rules[rule_]()
								{
									add(ruleAction11, position)
								}
								add(ruleEVERYTHING, position4)
							}
						case 'n':
							{
								position7 := position
								{
									position8, tokenIndex8 := position, tokenIndex
									if !_rules[ruleNEXT]() {
										goto l9
									}
									{
										position10, tokenIndex10 := position, tokenIndex
										if !_rules[ruleNumber]() {
											goto l10
										}
										goto l11
									l10:
										position, tokenIndex = position10, tokenIndex10
									}
								l11:
									if !_rules[ruleYEARS]() {
										goto l9
									}
									{
										add(ruleAction7, position)
									}
									goto l8
								l9:
									position, tokenIndex = position8, tokenIndex8
									if !_rules[ruleNEXT]() {
										goto l13
									}
									{
										position14, tokenIndex14 := position, tokenIndex
										if !_rules[ruleNumber]() {
											goto l14
										}
										goto l15
									l14:
										position, tokenIndex = position14, tokenIndex14
									}
								l15:
									if !_rules[ruleQUARTERS]() {
										goto l13
									}
									{
										add(ruleAction8, position)
									}
									goto l8
								l13:
									position, tokenIndex = position8, tokenIndex8
									if !_rules[ruleNEXT]() {
										goto l17
									}
									{
										position18, tokenIndex18 := position, tokenIndex
										if !_rules[ruleNumber]() {
											goto l18
										}
										goto l19
									l18:
										position, tokenIndex = position18, tokenIndex18
									}
								l19:
									if !_rules[ruleMONTHS]() {
										goto l17
									}
									{
										add(ruleAction9, position)
									}
									goto l8
								l17:
									position, tokenIndex = position8, tokenIndex8
									if !_rules[ruleNEXT]() {
										goto l0
									}
									{
										position21, tokenIndex21 := position, tokenIndex
										if !_rules[ruleNumber]() {
											goto l21
										}
										goto l22
									l21:
										position, tokenIndex = position21, tokenIndex21
									}
								l22:
									if !_rules[ruleWEEKS]() {
										goto l0
									}
									{
										add(ruleAction10, position)
									}
								}
							l8:
								add(ruleFUTURE, position7)
							}
						case 'l', 'p':
							{
								position24 := position
								{
									position25, tokenIndex25 := position, tokenIndex
									if !_rules[ruleLAST]() {
										goto l26
									}
									{
										position27, tokenIndex27 := position, tokenIndex
										if !_rules[ruleNumber]() {
											goto l27
										}
										goto l28
									l27:
										position, tokenIndex = position27, tokenIndex27
									}
								l28:
									if !_rules[ruleYEARS]() {
										goto l26
									}
									{
										add(ruleAction3, position)
									}
									goto l25
								l26:
									position, tokenIndex = position25, tokenIndex25
									if !_rules[ruleLAST]() {
										goto l30
									}
									{
										position31, tokenIndex31 := position, tokenIndex
										if !_rules[ruleNumber]() {
											goto l31
										}
										goto l32
									l31:
										position, tokenIndex = position31, tokenIndex31
									}
								l32:
									if !_rules[ruleQUARTERS]() {
										goto l30
									}
									{
										add(ruleAction4, position)
									}
									goto l25
								l30:
									position, tokenIndex = position25, tokenIndex25
									if !_rules[ruleLAST]() {
										goto l34
									}
									{
										position35, tokenIndex35 := position, tokenIndex
										if !_rules[ruleNumber]() {
											goto l35
										}
										goto l36
									l35:
										position, tokenIndex = position35, tokenIndex35
									}
								l36:
									if !_rules[ruleMONTHS]() {
										goto l34
									}
									{
										add(ruleAction5, position)
									}
									goto l25
								l34:
									position, tokenIndex = position25, tokenIndex25
									if !_rules[ruleLAST]() {
										goto l0
									}
									{
										position38, tokenIndex38 := position, tokenIndex
										if !_rules[ruleNumber]() {
											goto l38
										}
										goto l39
									l38:
										position, tokenIndex = position38, tokenIndex38
									}
								l39:
									if !_rules[ruleWEEKS]() {
										goto l0
									}
									{
										add(ruleAction6, position)
									}
								}
							l25:
								add(rulePAST, position24)
							}
						default:
							{
								position41 := position
								{
									position42, tokenIndex42 := position, tokenIndex
									{
										position44, tokenIndex44 := position, tokenIndex
										if !_rules[ruleCURRENT]() {
											goto l45
										}
										if !_rules[ruleYEARS]() {
											goto l45
										}
										goto l44
									l45:
										position, tokenIndex = position44, tokenIndex44
										if !_rules[ruleYEARS]() {
											goto l46
										}
										if !_rules[ruleTODATE]() {
											goto l46
										}
										goto l44
									l46:
										position, tokenIndex = position44, tokenIndex44
										if buffer[position] != 'y' {
											goto l43
										}
										position++
										if buffer[position] != 't' {
											goto l43
										}
										position++
										if buffer[position] != 'd' {
											goto l43
										}
										position++
										_rules[rule_]()
									}
								l44:
									{
										add(ruleAction0, position)
									}
									goto l42
								l43:
									position, tokenIndex = position42, tokenIndex42
									{
										position49, tokenIndex49 := position, tokenIndex
										if !_rules[ruleCURRENT]() {
											goto l50
										}
										if !_rules[ruleQUARTERS]() {
											goto l50
										}
										goto l49
									l50:
										position, tokenIndex = position49, tokenIndex49
										if !_rules[ruleQUARTERS]() {
											goto l51
										}
										if !_rules[ruleTODATE]() {
											goto l51
										}
										goto l49
									l51:
										position, tokenIndex = position49, tokenIndex49
										if buffer[position] != 'q' {
											goto l48
										}
										position++
										if buffer[position] != 't' {
											goto l48
										}
										position++
										if buffer[position] != 'd' {
											goto l48
										}
										position++
										_rules[rule_]()
									}
								l49:
									{
										add(ruleAction1, position)
									}
									goto l42
								l48:
									position, tokenIndex = position42, tokenIndex42
									{
										position53, tokenIndex53 := position, tokenIndex
										if !_rules[ruleCURRENT]() {
											goto l54
										}
										if !_rules[ruleMONTHS]() {
											goto l54
										}
										goto l53
									l54:
										position, tokenIndex = position53, tokenIndex53
										if !_rules[ruleMONTHS]() {
											goto l55
										}
										if !_rules[ruleTODATE]() {
											goto l55
										}
										goto l53
									l55:
										position, tokenIndex = position53, tokenIndex53
										if buffer[position] != 'm' {
											goto l0
										}
										position++
										if buffer[position] != 't' {
											goto l0
										}
										position++
										if buffer[position] != 'd' {
											goto l0
										}
										position++
										_rules[rule_]()
									}
								l53:
									{
										add(ruleAction2, position)
									}
								}
							l42:
								add(ruleNOW, position41)
							}
						}
					}

					add(ruleExpr, position2)
				}
				{
					position57 := position
					{
						position58, tokenIndex58 := position, tokenIndex
						if !matchDot() {
							goto l58
						}
						goto l0
					l58:
						position, tokenIndex = position58, tokenIndex58
					}
					add(ruleEOF, position57)
				}
				add(ruleQuery, position1)
			}
			memoize(0, position0, tokenIndex0, true)
			return true
		l0:
			memoize(0, position0, tokenIndex0, false)
			position, tokenIndex = position0, tokenIndex0
			return false
		},
		/* 1 Expr <- <((&('a' | 'e' | 'f') EVERYTHING) | (&('n') FUTURE) | (&('l' | 'p') PAST) | (&('c' | 'm' | 'q' | 'y') NOW))> */
		nil,
		/* 2 NOW <- <((((CURRENT YEARS) / (YEARS TODATE) / ('y' 't' 'd' _)) Action0) / (((CURRENT QUARTERS) / (QUARTERS TODATE) / ('q' 't' 'd' _)) Action1) / (((CURRENT MONTHS) / (MONTHS TODATE) / ('m' 't' 'd' _)) Action2))> */
		nil,
		/* 3 PAST <- <((LAST Number? YEARS Action3) / (LAST Number? QUARTERS Action4) / (LAST Number? MONTHS Action5) / (LAST Number? WEEKS Action6))> */
		nil,
		/* 4 FUTURE <- <((NEXT Number? YEARS Action7) / (NEXT Number? QUARTERS Action8) / (NEXT Number? MONTHS Action9) / (NEXT Number? WEEKS Action10))> */
		nil,
		/* 5 EVERYTHING <- <(((&('e') ('e' 'v' 'e' 'r' 'y' 't' 'h' 'i' 'n' 'g')) | (&('f') ('f' 'o' 'r' 'e' 'v' 'e' 'r')) | (&('a') ('a' 'l' 'l' ' ' 't' 'i' 'm' 'e'))) _ Action11)> */
		nil,
		/* 6 Number <- <(('t' 'w' 'o' _ Action14) / ('t' 'h' 'r' 'e' 'e' _ Action15) / ('f' 'o' 'u' 'r' _ Action16) / ('f' 'i' 'v' 'e' _ Action17) / ('s' 'i' 'x' _ Action18) / ('s' 'e' 'v' 'e' 'n' _ Action19) / ('e' 'i' 'g' 'h' 't' _ Action20) / ('n' 'i' 'n' 'e' _ Action21) / ('t' 'e' 'n' _ Action22) / ('e' 'l' 'e' 'v' 'e' 'n' _ Action23) / ('t' 'w' 'e' 'l' 'v' 'e' _ Action24) / ('t' 'h' 'i' 'r' 't' 'e' 'e' 'n' _ Action25) / ('f' 'o' 'u' 'r' 't' 'e' 'e' 'n' _ Action26) / ('s' 'i' 'x' 't' 'e' 'e' 'n' _ Action28) / ((&('t') ('t' 'w' 'e' 'n' 't' 'y' _ Action32)) | (&('n') ('n' 'i' 'n' 'e' 't' 'e' 'e' 'n' _ Action31)) | (&('e') ('e' 'i' 'g' 'h' 't' 't' 'e' 'e' 'n' _ Action30)) | (&('s') ('s' 'e' 'v' 'e' 'n' 't' 'e' 'e' 'n' _ Action29)) | (&('f') ('f' 'i' 'f' 't' 'e' 'e' 'n' _ Action27)) | (&('o') ('o' 'n' 'e' _ Action13)) | (&('0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9') (<[0-9]+> _ Action12))))> */
		func() bool {
			if memoized, ok := memoization[memoKey[U]{6, position}]; ok {
				return memoizedResult(memoized)
			}
			position64, tokenIndex64 := position, tokenIndex
			{
				position65 := position
				{
					position66, tokenIndex66 := position, tokenIndex
					if buffer[position] != 't' {
						goto l67
					}
					position++
					if buffer[position] != 'w' {
						goto l67
					}
					position++
					if buffer[position] != 'o' {
						goto l67
					}
					position++
					_rules[rule_]()
					{
						add(ruleAction14, position)
					}
					goto l66
				l67:
					position, tokenIndex = position66, tokenIndex66
					if buffer[position] != 't' {
						goto l69
					}
					position++
					if buffer[position] != 'h' {
						goto l69
					}
					position++
					if buffer[position] != 'r' {
						goto l69
					}
					position++
					if buffer[position] != 'e' {
						goto l69
					}
					position++
					if buffer[position] != 'e' {
						goto l69
					}
					position++
					_rules[rule_]()
					{
						add(ruleAction15, position)
					}
					goto l66
				l69:
					position, tokenIndex = position66, tokenIndex66
					if buffer[position] != 'f' {
						goto l71
					}
					position++
					if buffer[position] != 'o' {
						goto l71
					}
					position++
					if buffer[position] != 'u' {
						goto l71
					}
					position++
					if buffer[position] != 'r' {
						goto l71
					}
					position++
					_rules[rule_]()
					{
						add(ruleAction16, position)
					}
					goto l66
				l71:
					position, tokenIndex = position66, tokenIndex66
					if buffer[position] != 'f' {
						goto l73
					}
					position++
					if buffer[position] != 'i' {
						goto l73
					}
					position++
					if buffer[position] != 'v' {
						goto l73
					}
					position++
					if buffer[position] != 'e' {
						goto l73
					}
					position++
					_rules[rule_]()
					{
						add(ruleAction17, position)
					}
					goto l66
				l73:
					position, tokenIndex = position66, tokenIndex66
					if buffer[position] != 's' {
						goto l75
					}
					position++
					if buffer[position] != 'i' {
						goto l75
					}
					position++
					if buffer[position] != 'x' {
						goto l75
					}
					position++
					_rules[rule_]()
					{
						add(ruleAction18, position)
					}
					goto l66
				l75:
					position, tokenIndex = position66, tokenIndex66
					if buffer[position] != 's' {
						goto l77
					}
					position++
					if buffer[position] != 'e' {
						goto l77
					}
					position++
					if buffer[position] != 'v' {
						goto l77
					}
					position++
					if buffer[position] != 'e' {
						goto l77
					}
					position++
					if buffer[position] != 'n' {
						goto l77
					}
					position++
					_rules[rule_]()
					{
						add(ruleAction19, position)
					}
					goto l66
				l77:
					position, tokenIndex = position66, tokenIndex66
					if buffer[position] != 'e' {
						goto l79
					}
					position++
					if buffer[position] != 'i' {
						goto l79
					}
					position++
					if buffer[position] != 'g' {
						goto l79
					}
					position++
					if buffer[position] != 'h' {
						goto l79
					}
					position++
					if buffer[position] != 't' {
						goto l79
					}
					position++
					_rules[rule_]()
					{
						add(ruleAction20, position)
					}
					goto l66
				l79:
					position, tokenIndex = position66, tokenIndex66
					if buffer[position] != 'n' {
						goto l81
					}
					position++
					if buffer[position] != 'i' {
						goto l81
					}
					position++
					if buffer[position] != 'n' {
						goto l81
					}
					position++
					if buffer[position] != 'e' {
						goto l81
					}
					position++
					_rules[rule_]()
					{
						add(ruleAction21, position)
					}
					goto l66
				l81:
					position, tokenIndex = position66, tokenIndex66
					if buffer[position] != 't' {
						goto l83
					}
					position++
					if buffer[position] != 'e' {
						goto l83
					}
					position++
					if buffer[position] != 'n' {
						goto l83
					}
					position++
					_rules[rule_]()
					{
						add(ruleAction22, position)
					}
					goto l66
				l83:
					position, tokenIndex = position66, tokenIndex66
					if buffer[position] != 'e' {
						goto l85
					}
					position++
					if buffer[position] != 'l' {
						goto l85
					}
					position++
					if buffer[position] != 'e' {
						goto l85
					}
					position++
					if buffer[position] != 'v' {
						goto l85
					}
					position++
					if buffer[position] != 'e' {
						goto l85
					}
					position++
					if buffer[position] != 'n' {
						goto l85
					}
					position++
					_rules[rule_]()
					{
						add(ruleAction23, position)
					}
					goto l66
				l85:
					position, tokenIndex = position66, tokenIndex66
					if buffer[position] != 't' {
						goto l87
					}
					position++
					if buffer[position] != 'w' {
						goto l87
					}
					position++
					if buffer[position] != 'e' {
						goto l87
					}
					position++
					if buffer[position] != 'l' {
						goto l87
					}
					position++
					if buffer[position] != 'v' {
						goto l87
					}
					position++
					if buffer[position] != 'e' {
						goto l87
					}
					position++
					_rules[rule_]()
					{
						add(ruleAction24, position)
					}
					goto l66
				l87:
					position, tokenIndex = position66, tokenIndex66
					if buffer[position] != 't' {
						goto l89
					}
					position++
					if buffer[position] != 'h' {
						goto l89
					}
					position++
					if buffer[position] != 'i' {
						goto l89
					}
					position++
					if buffer[position] != 'r' {
						goto l89
					}
					position++
					if buffer[position] != 't' {
						goto l89
					}
					position++
					if buffer[position] != 'e' {
						goto l89
					}
					position++
					if buffer[position] != 'e' {
						goto l89
					}
					position++
					if buffer[position] != 'n' {
						goto l89
					}
					position++
					_rules[rule_]()
					{
						add(ruleAction25, position)
					}
					goto l66
				l89:
					position, tokenIndex = position66, tokenIndex66
					if buffer[position] != 'f' {
						goto l91
					}
					position++
					if buffer[position] != 'o' {
						goto l91
					}
					position++
					if buffer[position] != 'u' {
						goto l91
					}
					position++
					if buffer[position] != 'r' {
						goto l91
					}
					position++
					if buffer[position] != 't' {
						goto l91
					}
					position++
					if buffer[position] != 'e' {
						goto l91
					}
					position++
					if buffer[position] != 'e' {
						goto l91
					}
					position++
					if buffer[position] != 'n' {
						goto l91
					}
					position++
					_rules[rule_]()
					{
						add(ruleAction26, position)
					}
					goto l66
				l91:
					position, tokenIndex = position66, tokenIndex66
					if buffer[position] != 's' {
						goto l93
					}
					position++
					if buffer[position] != 'i' {
						goto l93
					}
					position++
					if buffer[position] != 'x' {
						goto l93
					}
					position++
					if buffer[position] != 't' {
						goto l93
					}
					position++
					if buffer[position] != 'e' {
						goto l93
					}
					position++
					if buffer[position] != 'e' {
						goto l93
					}
					position++
					if buffer[position] != 'n' {
						goto l93
					}
					position++
					_rules[rule_]()
					{
						add(ruleAction28, position)
					}
					goto l66
				l93:
					position, tokenIndex = position66, tokenIndex66
					{
						switch buffer[position] {
						case 't':
							position++
							if buffer[position] != 'w' {
								goto l64
							}
							position++
							if buffer[position] != 'e' {
								goto l64
							}
							position++
							if buffer[position] != 'n' {
								goto l64
							}
							position++
							if buffer[position] != 't' {
								goto l64
							}
							position++
							if buffer[position] != 'y' {
								goto l64
							}
							position++
							_rules[rule_]()
							{
								add(ruleAction32, position)
							}
						case 'n':
							position++
							if buffer[position] != 'i' {
								goto l64
							}
							position++
							if buffer[position] != 'n' {
								goto l64
							}
							position++
							if buffer[position] != 'e' {
								goto l64
							}
							position++
							if buffer[position] != 't' {
								goto l64
							}
							position++
							if buffer[position] != 'e' {
								goto l64
							}
							position++
							if buffer[position] != 'e' {
								goto l64
							}
							position++
							if buffer[position] != 'n' {
								goto l64
							}
							position++
							_rules[rule_]()
							{
								add(ruleAction31, position)
							}
						case 'e':
							position++
							if buffer[position] != 'i' {
								goto l64
							}
							position++
							if buffer[position] != 'g' {
								goto l64
							}
							position++
							if buffer[position] != 'h' {
								goto l64
							}
							position++
							if buffer[position] != 't' {
								goto l64
							}
							position++
							if buffer[position] != 't' {
								goto l64
							}
							position++
							if buffer[position] != 'e' {
								goto l64
							}
							position++
							if buffer[position] != 'e' {
								goto l64
							}
							position++
							if buffer[position] != 'n' {
								goto l64
							}
							position++
							_rules[rule_]()
							{
								add(ruleAction30, position)
							}
						case 's':
							position++
							if buffer[position] != 'e' {
								goto l64
							}
							position++
							if buffer[position] != 'v' {
								goto l64
							}
							position++
							if buffer[position] != 'e' {
								goto l64
							}
							position++
							if buffer[position] != 'n' {
								goto l64
							}
							position++
							if buffer[position] != 't' {
								goto l64
							}
							position++
							if buffer[position] != 'e' {
								goto l64
							}
							position++
							if buffer[position] != 'e' {
								goto l64
							}
							position++
							if buffer[position] != 'n' {
								goto l64
							}
							position++
							_rules[rule_]()
							{
								add(ruleAction29, position)
							}
						case 'f':
							position++
							if buffer[position] != 'i' {
								goto l64
							}
							position++
							if buffer[position] != 'f' {
								goto l64
							}
							position++
							if buffer[position] != 't' {
								goto l64
							}
							position++
							if buffer[position] != 'e' {
								goto l64
							}
							position++
							if buffer[position] != 'e' {
								goto l64
							}
							position++
							if buffer[position] != 'n' {
								goto l64
							}
							position++
							_rules[rule_]()
							{
								add(ruleAction27, position)
							}
						case 'o':
							position++
							if buffer[position] != 'n' {
								goto l64
							}
							position++
							if buffer[position] != 'e' {
								goto l64
							}
							position++
							_rules[rule_]()
							{
								add(ruleAction13, position)
							}
						default:
							{
								position102 := position
								if c := buffer[position]; c < '0' || c > '9' {
									goto l64
								}
								position++
							l103:
								{
									position104, tokenIndex104 := position, tokenIndex
									if c := buffer[position]; c < '0' || c > '9' {
										goto l104
									}
									position++
									goto l103
								l104:
									position, tokenIndex = position104, tokenIndex104
								}
								add(rulePegText, position102)
							}
							_rules[rule_]()
							{
								add(ruleAction12, position)
							}
						}
					}

				}
			l66:
				add(ruleNumber, position65)
			}
			memoize(6, position64, tokenIndex64, true)
			return true
		l64:
			memoize(6, position64, tokenIndex64, false)
			position, tokenIndex = position64, tokenIndex64
			return false
		},
		/* 7 YEARS <- <('y' 'e' 'a' 'r' 's'? _)> */
		func() bool {
			if memoized, ok := memoization[memoKey[U]{7, position}]; ok {
				return memoizedResult(memoized)
			}
			position106, tokenIndex106 := position, tokenIndex
			{
				position107 := position
				if buffer[position] != 'y' {
					goto l106
				}
				position++
				if buffer[position] != 'e' {
					goto l106
				}
				position++
				if buffer[position] != 'a' {
					goto l106
				}
				position++
				if buffer[position] != 'r' {
					goto l106
				}
				position++
				{
					position108, tokenIndex108 := position, tokenIndex
					if buffer[position] != 's' {
						goto l108
					}
					position++
					goto l109
				l108:
					position, tokenIndex = position108, tokenIndex108
				}
			l109:
				_rules[rule_]()
				add(ruleYEARS, position107)
			}
			memoize(7, position106, tokenIndex106, true)
			return true
		l106:
			memoize(7, position106, tokenIndex106, false)
			position, tokenIndex = position106, tokenIndex106
			return false
		},
		/* 8 QUARTERS <- <('q' 'u' 'a' 'r' 't' 'e' 'r' 's'? _)> */
		func() bool {
			if memoized, ok := memoization[memoKey[U]{8, position}]; ok {
				return memoizedResult(memoized)
			}
			position110, tokenIndex110 := position, tokenIndex
			{
				position111 := position
				if buffer[position] != 'q' {
					goto l110
				}
				position++
				if buffer[position] != 'u' {
					goto l110
				}
				position++
				if buffer[position] != 'a' {
					goto l110
				}
				position++
				if buffer[position] != 'r' {
					goto l110
				}
				position++
				if buffer[position] != 't' {
					goto l110
				}
				position++
				if buffer[position] != 'e' {
					goto l110
				}
				position++
				if buffer[position] != 'r' {
					goto l110
				}
				position++
				{
					position112, tokenIndex112 := position, tokenIndex
					if buffer[position] != 's' {
						goto l112
					}
					position++
					goto l113
				l112:
					position, tokenIndex = position112, tokenIndex112
				}
			l113:
				_rules[rule_]()
				add(ruleQUARTERS, position111)
			}
			memoize(8, position110, tokenIndex110, true)
			return true
		l110:
			memoize(8, position110, tokenIndex110, false)
			position, tokenIndex = position110, tokenIndex110
			return false
		},
		/* 9 MONTHS <- <('m' 'o' 'n' 't' 'h' 's'? _)> */
		func() bool {
			if memoized, ok := memoization[memoKey[U]{9, position}]; ok {
				return memoizedResult(memoized)
			}
			position114, tokenIndex114 := position, tokenIndex
			{
				position115 := position
				if buffer[position] != 'm' {
					goto l114
				}
				position++
				if buffer[position] != 'o' {
					goto l114
				}
				position++
				if buffer[position] != 'n' {
					goto l114
				}
				position++
				if buffer[position] != 't' {
					goto l114
				}
				position++
				if buffer[position] != 'h' {
					goto l114
				}
				position++
				{
					position116, tokenIndex116 := position, tokenIndex
					if buffer[position] != 's' {
						goto l116
					}
					position++
					goto l117
				l116:
					position, tokenIndex = position116, tokenIndex116
				}
			l117:
				_rules[rule_]()
				add(ruleMONTHS, position115)
			}
			memoize(9, position114, tokenIndex114, true)
			return true
		l114:
			memoize(9, position114, tokenIndex114, false)
			position, tokenIndex = position114, tokenIndex114
			return false
		},
		/* 10 WEEKS <- <('w' 'e' 'e' 'k' 's'? _)> */
		func() bool {
			if memoized, ok := memoization[memoKey[U]{10, position}]; ok {
				return memoizedResult(memoized)
			}
			position118, tokenIndex118 := position, tokenIndex
			{
				position119 := position
				if buffer[position] != 'w' {
					goto l118
				}
				position++
				if buffer[position] != 'e' {
					goto l118
				}
				position++
				if buffer[position] != 'e' {
					goto l118
				}
				position++
				if buffer[position] != 'k' {
					goto l118
				}
				position++
				{
					position120, tokenIndex120 := position, tokenIndex
					if buffer[position] != 's' {
						goto l120
					}
					position++
					goto l121
				l120:
					position, tokenIndex = position120, tokenIndex120
				}
			l121:
				_rules[rule_]()
				add(ruleWEEKS, position119)
			}
			memoize(10, position118, tokenIndex118, true)
			return true
		l118:
			memoize(10, position118, tokenIndex118, false)
			position, tokenIndex = position118, tokenIndex118
			return false
		},
		/* 11 LAST <- <((('l' 'a' 's' 't') / ('p' 'r' 'e' 'v' 'i' 'o' 'u' 's') / ('p' 'a' 's' 't')) _)> */
		func() bool {
			if memoized, ok := memoization[memoKey[U]{11, position}]; ok {
				return memoizedResult(memoized)
			}
			position122, tokenIndex122 := position, tokenIndex
			{
				position123 := position
				{
					position124, tokenIndex124 := position, tokenIndex
					if buffer[position] != 'l' {
						goto l125
					}
					position++
					if buffer[position] != 'a' {
						goto l125
					}
					position++
					if buffer[position] != 's' {
						goto l125
					}
					position++
					if buffer[position] != 't' {
						goto l125
					}
					position++
					goto l124
				l125:
					position, tokenIndex = position124, tokenIndex124
					if buffer[position] != 'p' {
						goto l126
					}
					position++
					if buffer[position] != 'r' {
						goto l126
					}
					position++
					if buffer[position] != 'e' {
						goto l126
					}
					position++
					if buffer[position] != 'v' {
						goto l126
					}
					position++
					if buffer[position] != 'i' {
						goto l126
					}
					position++
					if buffer[position] != 'o' {
						goto l126
					}
					position++
					if buffer[position] != 'u' {
						goto l126
					}
					position++
					if buffer[position] != 's' {
						goto l126
					}
					position++
					goto l124
				l126:
					position, tokenIndex = position124, tokenIndex124
					if buffer[position] != 'p' {
						goto l122
					}
					position++
					if buffer[position] != 'a' {
						goto l122
					}
					position++
					if buffer[position] != 's' {
						goto l122
					}
					position++
					if buffer[position] != 't' {
						goto l122
					}
					position++
				}
			l124:
				_rules[rule_]()
				add(ruleLAST, position123)
			}
			memoize(11, position122, tokenIndex122, true)
			return true
		l122:
			memoize(11, position122, tokenIndex122, false)
			position, tokenIndex = position122, tokenIndex122
			return false
		},
		/* 12 CURRENT <- <('c' 'u' 'r' 'r' 'e' 'n' 't' _)> */
		func() bool {
			if memoized, ok := memoization[memoKey[U]{12, position}]; ok {
				return memoizedResult(memoized)
			}
			position127, tokenIndex127 := position, tokenIndex
			{
				position128 := position
				if buffer[position] != 'c' {
					goto l127
				}
				position++
				if buffer[position] != 'u' {
					goto l127
				}
				position++
				if buffer[position] != 'r' {
					goto l127
				}
				position++
				if buffer[position] != 'r' {
					goto l127
				}
				position++
				if buffer[position] != 'e' {
					goto l127
				}
				position++
				if buffer[position] != 'n' {
					goto l127
				}
				position++
				if buffer[position] != 't' {
					goto l127
				}
				position++
				_rules[rule_]()
				add(ruleCURRENT, position128)
			}
			memoize(12, position127, tokenIndex127, true)
			return true
		l127:
			memoize(12, position127, tokenIndex127, false)
			position, tokenIndex = position127, tokenIndex127
			return false
		},
		/* 13 TODATE <- <('t' 'o' ' ' 'd' 'a' 't' 'e' _)> */
		func() bool {
			if memoized, ok := memoization[memoKey[U]{13, position}]; ok {
				return memoizedResult(memoized)
			}
			position129, tokenIndex129 := position, tokenIndex
			{
				position130 := position
				if buffer[position] != 't' {
					goto l129
				}
				position++
				if buffer[position] != 'o' {
					goto l129
				}
				position++
				if buffer[position] != ' ' {
					goto l129
				}
				position++
				if buffer[position] != 'd' {
					goto l129
				}
				position++
				if buffer[position] != 'a' {
					goto l129
				}
				position++
				if buffer[position] != 't' {
					goto l129
				}
				position++
				if buffer[position] != 'e' {
					goto l129
				}
				position++
				_rules[rule_]()
				add(ruleTODATE, position130)
			}
			memoize(13, position129, tokenIndex129, true)
			return true
		l129:
			memoize(13, position129, tokenIndex129, false)
			position, tokenIndex = position129, tokenIndex129
			return false
		},
		/* 14 NEXT <- <('n' 'e' 'x' 't' _)> */
		func() bool {
			if memoized, ok := memoization[memoKey[U]{14, position}]; ok {
				return memoizedResult(memoized)
			}
			position131, tokenIndex131 := position, tokenIndex
			{
				position132 := position
				if buffer[position] != 'n' {
					goto l131
				}
				position++
				if buffer[position] != 'e' {
					goto l131
				}
				position++
				if buffer[position] != 'x' {
					goto l131
				}
				position++
				if buffer[position] != 't' {
					goto l131
				}
				position++
				_rules[rule_]()
				add(ruleNEXT, position132)
			}
			memoize(14, position131, tokenIndex131, true)
			return true
		l131:
			memoize(14, position131, tokenIndex131, false)
			position, tokenIndex = position131, tokenIndex131
			return false
		},
		/* 15 _ <- <Whitespace*> */
		func() bool {
			if memoized, ok := memoization[memoKey[U]{15, position}]; ok {
				return memoizedResult(memoized)
			}
			position133, tokenIndex133 := position, tokenIndex
			{
				position134 := position
			l135:
				{
					position136, tokenIndex136 := position, tokenIndex
					{
						position137 := position
						{
							switch buffer[position] {
							case '\t':
								position++
							case ' ':
								position++
							default:
								{
									position139 := position
									{
										position140, tokenIndex140 := position, tokenIndex
										if buffer[position] != '\r' {
											goto l141
										}
										position++
										if buffer[position] != '\n' {
											goto l141
										}
										position++
										goto l140
									l141:
										position, tokenIndex = position140, tokenIndex140
										if buffer[position] != '\n' {
											goto l142
										}
										position++
										goto l140
									l142:
										position, tokenIndex = position140, tokenIndex140
										if buffer[position] != '\r' {
											goto l136
										}
										position++
									}
								l140:
									add(ruleEOL, position139)
								}
							}
						}

						add(ruleWhitespace, position137)
					}
					goto l135
				l136:
					position, tokenIndex = position136, tokenIndex136
				}
				add(rule_, position134)
			}
			memoize(15, position133, tokenIndex133, true)
			return true
		},
		/* 16 Whitespace <- <((&('\t') '\t') | (&(' ') ' ') | (&('\n' | '\r') EOL))> */
		nil,
		/* 17 EOL <- <(('\r' '\n') / '\n' / '\r')> */
		nil,
		/* 18 EOF <- <!.> */
		nil,
		/* 20 Action0 <- <{
			p.start, p.end = boundsYear(p.currentTime)
		}> */
		nil,
		/* 21 Action1 <- <{
			p.start, p.end = boundsQuarter(p.currentTime)
		}> */
		nil,
		/* 22 Action2 <- <{
			p.start, p.end = boundsMonth(p.currentTime)
		}> */
		nil,
		/* 23 Action3 <- <{
			p.start, p.end = boundsYear(p.currentTime)
			if p.number > 1 {
				p.start = p.start.AddDate(-1*(p.number-1), 0, 0)
			} else {
				p.end = p.start
				p.start = p.start.AddDate(-1, 0, 0)
			}
		}> */
		nil,
		/* 24 Action4 <- <{
			p.start, p.end = boundsQuarter(p.currentTime)
			if p.number > 1 {
				p.start = p.start.AddDate(0, -3*(p.number-1), 0)
			} else {
				p.end = p.start
				p.start = p.start.AddDate(0,-3,0)
			}
		}> */
		nil,
		/* 25 Action5 <- <{
			p.start, p.end = boundsMonth(p.currentTime)
			if p.number > 1 {
				p.start = p.start.AddDate(0, -1*(p.number-1), 0)
			} else {
				p.end = p.start
				p.start = p.start.AddDate(0, -1, 0)
			}
		}> */
		nil,
		/* 26 Action6 <- <{
			p.start, p.end = boundsWeek(p.currentTime)
			if p.number > 1 {
				p.start = p.start.AddDate(0, 0, -7*(p.number-1))
			} else {
				p.end = p.start
				p.start = p.start.AddDate(0, 0, -7)
			}
		}> */
		nil,
		/* 27 Action7 <- <{
			p.start, p.end = boundsYear(p.currentTime)
			if p.number > 1 {
				p.end = p.start.AddDate(p.number, 0, 0)
			} else {
				p.start = p.end
				p.end = p.start.AddDate(1, 0, 0)
			}
		}> */
		nil,
		/* 28 Action8 <- <{
			p.start, p.end = boundsQuarter(p.currentTime)
			if p.number > 1 {
				p.end = p.start.AddDate(0,3*(p.number),0)
			} else {
				p.start = p.start.AddDate(0,3,0)
				p.end = p.start.AddDate(0,3,0)
			}
		}> */
		nil,
		/* 29 Action9 <- <{
			p.start, p.end = boundsMonth(p.currentTime)
			if p.number > 1 {
				p.end = p.start.AddDate(0, p.number, 0)
			} else {
				p.start = p.end
				p.end = p.start.AddDate(0, 1, 0)
			}
		}> */
		nil,
		/* 30 Action10 <- <{
			p.start, p.end = boundsWeek(p.currentTime)
			if p.number > 1 {
				p.end = p.start.AddDate(0, 0, 7*p.number)
			} else {
				p.start = p.end
				p.end = p.start.AddDate(0, 0, 7)
			}
		}> */
		nil,
		/* 31 Action11 <- <{
			p.start = time.Time{}
			p.end = p.currentTime.Add(1<<63 -1)
		}> */
		nil,
		nil,
		/* 33 Action12 <- <{ n, _ := strconv.Atoi(text); p.number = n}> */
		nil,
		/* 34 Action13 <- <{ p.number = 1 }> */
		nil,
		/* 35 Action14 <- <{ p.number = 2 }> */
		nil,
		/* 36 Action15 <- <{ p.number = 3 }> */
		nil,
		/* 37 Action16 <- <{ p.number = 4 }> */
		nil,
		/* 38 Action17 <- <{ p.number = 5 }> */
		nil,
		/* 39 Action18 <- <{ p.number = 6 }> */
		nil,
		/* 40 Action19 <- <{ p.number = 7 }> */
		nil,
		/* 41 Action20 <- <{ p.number = 8 }> */
		nil,
		/* 42 Action21 <- <{ p.number = 9 }> */
		nil,
		/* 43 Action22 <- <{ p.number = 10 }> */
		nil,
		/* 44 Action23 <- <{ p.number = 11 }> */
		nil,
		/* 45 Action24 <- <{ p.number = 12 }> */
		nil,
		/* 46 Action25 <- <{ p.number = 13 }> */
		nil,
		/* 47 Action26 <- <{ p.number = 14 }> */
		nil,
		/* 48 Action27 <- <{ p.number = 15 }> */
		nil,
		/* 49 Action28 <- <{ p.number = 16 }> */
		nil,
		/* 50 Action29 <- <{ p.number = 17 }> */
		nil,
		/* 51 Action30 <- <{ p.number = 18 }> */
		nil,
		/* 52 Action31 <- <{ p.number = 19 }> */
		nil,
		/* 53 Action32 <- <{ p.number = 20 }> */
		nil,
	}
	p.rules = _rules
	return nil
}
