.Dd June 25, 2021
.Dt LEDGER 1
.Os
.Sh NAME
.Nm ledger
.Nd Command-line, double-entry accounting tool
.Sh SYNOPSIS
.Nm
.Op Ar options
.Op Ar command
.Op Ar arguments
.Sh DESCRIPTION
.Nm
is a command-line accounting tool based on the power and completeness
of double-entry accounting.  It is only a reporting tool, which means it never
modifies your data files, but it does offer a large selection of reports, and
different ways to customize them to your needs. It also offers a command to 
import a csv file and output them into ledger format. Plus a web service
interface to view reports with charts/tables.
.Sh REPORT COMMANDS
.Nm
accepts several top-level commands, each of which generates a different
kind of basic report.  Most of them accept an optional
.Ar account-filter
argument, in order to determine what should be reported.  To understand the
syntax of a
.Ar account-filter ,
see the section on
.Sx FILTERS .
In its most basic form, simply specifying one or more strings produces a
report for all accounts containing those strings.
.Pp
The following is a complete list of reporting commands:
.Bl -tag -width balance
.It Ic accounts Oo Ar account-filter Oc
Print a list of sorted accounts for postings that match
.Ar account-filter . 
Options available for this command are:
.Bl -tag -compact -width "--begin-date (b) YYYY-mm-dd "
.It Fl \-begin-date ( Fl b ) Ar YYYY-mm-dd
Begin date of transactions to include in processing.
.It Fl \-end-date ( Fl e ) Ar YYYY-mm-dd
End date of transactions to include in processing.
.It Fl \-leaves-only Pq Fl l
Only show accounts with highest depth in a given account hierarchy.
.It Fl \-match-depth Pq Fl m
Requires one
.Ar account-filter
to be specified. Prints accounts that match the same depth (separators)
of supplied filter.
.El
.Pp
The
.Ic accounts
command is used to provide autocomplete functionality in the vim-ledger plugin.
.It Ic balance Oo Ar account-filter Oc
Print a balance report showing totals for postings that match
.Ar account-filter ,
and aggregate totals for parents of those accounts.  Options available for 
this command are:
.Bl -tag -compact -width "--begin-date (b) YYYY-mm-dd "
.It Fl \-begin-date ( Fl b ) Ar YYYY-mm-dd
Begin date of transactions to include in processing.
.It Fl \-columns Ar INT
Width of output in characters.
.It Fl \-depth Ar INT
Limit the depth of the account tree.  In a balance report, for example,
.Fl \-depth Ar 2
will print balances only for accounts with two levels, i.e.
.Sy Expenses:Entertainment
but not
.Sy Expenses:Entertainment:Dining .
This is a display predicate, which means it only affects display,
not the total calculations.  In register reports,
.It Fl \-empty
Show accounts whose total is zero.
.It Fl \-end-date ( Fl e ) Ar YYYY-mm-dd
End date of transactions to include in processing.
.It Fl \-payee Ar STR
Filter transactions used in processing to payees that contain this string.
.It Fl \-period Ar STR
Split output into multiple results based on specified period. Valid options are:
.Sy Monthly ,
.Sy Quarterly ,
.Sy SemiYearly ,
.Sy Yearly
.It Fl \-wide
Alias for --columns=132
.El
.Pp
The alias
.Ic bal
is also accepted.
.It Ic equity
Print a transaction with a series of postings that balance current totals for
accounts. The purpose of this report is to close the books for a prior year, while using
these equity postings to carry forward those balances. Options available for this
command are:
.Bl -tag -compact -width "--begin-date (b) YYYY-mm-dd "
.It Fl \-begin-date ( Fl b ) Ar YYYY-mm-dd
Begin date of transactions to include in processing.
.It Fl \-end-date ( Fl e ) Ar YYYY-mm-dd
End date of transactions to include in processing.
.El
.It Ic lint
Parse the 
.Nm
file and output any parsing errors.
.It Ic print Oo Ar account-filter Oc
Print out the full transactions of any matching postings using the same
format as they would appear in a data file.  This can be used to extract
subsets from a
.Nm
file to transfer to other files.  Options available for 
this command are:
.Bl -tag -compact -width "--begin-date (b) YYYY-mm-dd "
.It Fl \-begin-date ( Fl b ) Ar YYYY-mm-dd
Begin date of transactions to include in processing.
.It Fl \-columns Ar INT
Width of output in characters.
.It Fl \-end-date ( Fl e ) Ar YYYY-mm-dd
End date of transactions to include in processing.
.It Fl \-payee Ar STR
Filter transactions used in processing to payees that contain this string.
.It Fl \-wide
Alias for --columns=132
.El
.It Ic register Oo Ar account-filter Oc
List all postings matching the
.Ar account-filter .
This is one of the most common commands, and can be used to provide a variety
of useful reports. Options available for this command are:
.Bl -tag -compact -width "--begin-date (b) YYYY-mm-dd "
.It Fl \-begin-date ( Fl b ) Ar YYYY-mm-dd
Begin date of transactions to include in processing.
.It Fl \-columns Ar INT
Width of output in characters.
.It Fl \-end-date ( Fl e ) Ar YYYY-mm-dd
End date of transactions to include in processing.
.It Fl \-payee Ar STR
Filter transactions used in processing to payees that contain this string.
.It Fl \-period Ar STR
Split output into multiple results based on specified period. Valid options are:
.Sy Monthly ,
.Sy Quarterly ,
.Sy SemiYearly ,
.Sy Yearly
.It Fl \-wide
Alias for --columns=132
.El
.Pp
The alias
.Ic reg
is also accepted.
.It Ic stats
Provide summary information about all the postings.
It provides information such as:
.Bl -bullet -offset indent -compact
.It
Time range of all matching postings
.It
Unique payees
.It
Unique accounts
.It
Transactions total
.It
Postings total
.It
Days since last posting
.El
.It Ic version
Output version string.
.El
.Sh ADD TRANSACTIONS
.Nm
has a top-level command to convert csv formatted postings to tranaction format.
.Pp
Headers in the csv file are used to attempt automatic creation of transactions
for each line in the csv file. The import process looks for (not case sensitive)
the following fields, and uses them for the corresponding transaction
information.
.Bl -tag -width "description, payee"
.It date
Date string.
.It payee/description
Match against payee of existing transactions to guess the destination account
for the given transaction. Uses a clasifier that "learns" from existing ledger
file.
.It amount/expense
Value field. Amount used in transaction, after modified by
.Ar neg
or
.Ar scale
if the options are specified.
.It note/comment
Adds comments to the transaction if non-empty.
.El
.Bl -tag -width balance
.It Ic import <account-filter> <csv file>
Import transactions from csv. To aid in common transformations, the following
options are available:
.Bl -tag -compact -width "--collapsed FILE  (-n)"
.It Fl \-allow-matching
Prints all transactions even if they match existing transactions in the ledger
file. By default, only new transactions are printed.
.It Fl \-date-format Ar STR
Date format in csv file. Specified in Go time format style.
.It Fl \-delimeter Ar STR
Character delimeter between fields. Defaults is ","
.It Fl \-neg
Negate the value. Useful if input csv is positive, but transaction should be
negative, or vice versa.
.It Fl \-scale Ar factor
Multiplication factor to apply to values as they are transformed to
transactions.
.It Fl \-set-search Ar STR
Account prefix to use as basis of accounts to search against when
attempting to automatically categorize imported transactions.
Default is "Expense"
.El
.El
.Sh WEB SERVICE
.Nm
has a top-level command to run a web service.
.Bl -tag -width balance
.It Ic web
Run an html http service with charts/table reporting, stock portfolios, and 
account balance pages.
.Bl -tag -compact -width "--collapsed FILE  (-n)"
.It Fl \-localhost
Bind to localhost only. Defaults to listen on all IPs/interfaces.
.It Fl \-port Ar INT
Port to listen on for HTTP service.
.It Fl \-portfolio Ar FILE Pq Fl s
Configuration file specifying the mapping between account name and stock
information.
.It Fl \-quickview Ar FILE Pq Fl q
Configuration file specifying a list of accounts to show on index page. Replaces
the default index of all accounts with names specified. Shortnames can be
configured to be displayed in place of the hierarchical names.
.It Fl \-reports Ar FILE Pq Fl r
Configuration file specifying all the different reports. Accounts for each 
report, the chart type, and computed accounts can be configured for each report
defined.
.El
.El
.Pp
Example configuration files: web-porfolio-sample.toml, web-quickview-sample.toml, web-reports-sample.toml
.Sh OPTIONS
.Bl -tag -width -indent
.It Fl \-file Ar FILE Pq Fl f
Read journal data from
.Ar FILE .
.El
.Sh FILTERS
The syntax for reporting account filters.  It is a series of patterns
with an implicit OR operator between them.
.Bl -tag -width "term and term"
.It Ar pattern
A bare string is taken as a sub-expression matching the full account name.
Thus, to report the current balance for all assets and liabilities, you would
use:
.Pp
.Dl ledger bal Asset Liab
.El
.Pp
Note: string pattern matching is case-sensitive.
.Sh ENVIRONMENT
The default ledger file can be set as the environment variable
.Ar LEDGER_FILE
which can be overriden with
.Fl \-file Ar FILE Pq Fl f
on the command-line.  Options on the command-line always take precedence over
environment variable settings.
.Sh SEE ALSO
.Xr ledger 5
.Sh AUTHORS
.An "Chris Howey"
.Aq chris@howey.me
